# Generated by Django 4.1.7 on 2023-02-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPUHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_hours', models.FloatField()),
                ('logged_date', models.DateField()),
            ],
        ),
    ]
